name = "lifecarevalet-worker"

# IMPORTANT: 'main' line ko delete kar diya gaya hai.
# main = "functions/index.js" 

compatibility_date = "2025-01-01"
type = "module"

[[d1_databases]]
binding = "DB"  # <--- CRITICAL FIX: "lifecarevalet_db" se badal kar "DB" kiya gaya hai.
database_name = "lifecarevalet_db"
database_id = "25bfe850-5e59-435f-880c-48dc90739da7"
