name = "lifecarevalet-worker"
main = "functions/index.js" # Ise rehne do ya hata do
compatibility_date = "2025-01-01"
type = "module"

[[d1_databases]]
binding = "DB"  # <--- CRITICAL FIX: "DB" karna hai!
database_name = "lifecarevalet_db"
database_id = "25bfe850-5e59-435f-880c-48dc90739da7"
