name = "lifecarevalet-worker"

# YAHAN SE 'main = "functions/index.js"' LINE HATA DI GAYI HAI
# Kyunki hum Pages Functions use kar rahe hain, Worker nahi.

compatibility_date = "2025-01-01"
type = "module"

[[d1_databases]]
binding = "DB"  # <--- CRITICAL FIX: Pages Functions automaticallly is binding name ko use karte hain.
database_name = "lifecarevalet_db"
database_id = "25bfe850-5e59-435f-880c-48dc90739da7"
