name = "lifecarevalet-worker"
main = "functions/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "lifecarevalet_db"
database_name = "lifecarevalet"
database_id = "25bfe850-5e59-435f-880c-48dc90739da7"