name = "lifecarevalet-worker"
main = "functions/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "lifecarevalet_db"
database_name = "lifecarevalet_db"
database_id = "PASTE-YOUR-DB-ID-HERE"