name = "lifecarevalet-worker"
main = "functions/index.js"
compatibility_date = "2025-01-01"
type = "esm"   # ES Module required for D1 binding

[[d1_databases]]
binding = "lifecarevalet_db"
database_name = "lifecarevalet_db"   # same as Cloudflare D1 dashboard
database_id = "25bfe850-5e59-435f-880c-48dc90739da7"